Moved finfo _finfo_cache initialization at class creation level
jax-ml/ml_dtypes pull request #192
Opened 2024-09-13 17:03 UTC by vfdev-5

Description:
- Moved finfo _finfo_cache initialization at class creation level

> to avoid concurrency problems in the finfo cache, we should just preconstruct all the entries during module initialization, rather than on demand.

cc @hawkinsp

2024-09-13 18:46 UTC, jakevdp commented
We need to re-enable the multi threading tests before we can really test this.

The 0.5.0 release is in progress here: https://github.com/jax-ml/ml_dtypes/pull/194; just waiting on CI

2024-09-16 15:20 UTC, hawkinsp requested changes
Looks good; one small change.

2024-09-16 15:20 UTC, hawkinsp commented on ml_dtypes/_finfo.py
> +      t: init_fn.__func__() for t, init_fn in _finfo_type_map.items()
Can you add the `# pytype ...` comment from below? `pytype` doesn't know about `__func__`.

2024-09-16 15:50 UTC, hawkinsp approved these changes

2024-09-16 16:39 UTC, merged